### PR TITLE
Use std::rc now that Weak is stable

### PR DESCRIPTION
**Pull request by mbrubeck**

### CODE REVIEW

**Comment by Ygg01** [comment]
Thanks, didn't notice that. I'll get it reviewed, once I'm healthy again.

**Comment by Ygg01** [comment]
Well, I'm a bit better. It seems tests contain `extern crate rc`. Would you like me to change those?

**Comment by mbrubeck** [comment]
Fixed the tests.

**Comment by mbrubeck** [comment]
Rebased.

**Comment by Ygg01** [comment]
Oh, thank you :)

**Pull request merged**
