### PR TITLE
Added quiescent for parser interrupting

### PR DESCRIPTION
**Pull request by ConnorGBrewster**
WIP, do not merge yet!
Adds ability to interrupt the parser for scripts. Needed for servo/servo#10647.

### CODE REVIEW

**Comment by Ygg01** [comment]
No problem. Do you need any help adding that quiescent state?

**Comment by ConnorGBrewster** [comment]
@Ygg01 I am finishing hooking up the xml parser to Servo, but xml5ever didn't have the same script methods. I don't think that this is done completely right as many of the xml wpt tests still timeout, but I think it's a step in the right direction. I was wondering if someone could read over this code really quick and see if I am doing anything wrong.

cc @jdm

**Comment by Ygg01** [comment]
Which wpt tests? It could be that xml parser doesn't parse them correctly for some reason.

**Comment by ConnorGBrewster** [comment]
@Ygg01 pretty much any of the tests inside `dom/nodes` that ends with `-xhtml.xhtml`. It seems like the scripts are parsed fine, but some of them aren't ran. I have found some weird behavior where a script in the body would not run, but if I commented out one of the test harness scripts, then the javascript in the body would run.

**Comment by jdm** [comment]
These changes as written make sense to me. I suspect the problem still lies in the integration in Servo, rather than the implementation here.

**Comment by jdm** [comment]
Actually, https://github.com/ConnorGBrewster/xml5ever/blob/add_quiescent/src/tokenizer/mod.rs#L440 is missing an equivalent change from https://github.com/servo/html5ever/pull/107/files#diff-1346c48686bcf539a082442ec70b7e82L413 which could make a difference.

**Comment by ConnorGBrewster** [comment]
@jdm Ahh good catch! I added that, and removed the `mark_script_already_started` call because the spec says to only call that if the Xml Parser is using the fragment parsing algorithm, which does not seem to be implemented.

This seems to almost be there, the parser now pauses when it needs to prepare a script, but it does not resume, it just stops parsing after it hits the `Quiescent` state.

**Comment by ConnorGBrewster** [comment]
@Ygg01 @jdm This should be ready for review

**Comment by jdm** [comment]
The changes look good to me, but it might be nice to reduce the duplication in the script tag processing.

**Comment by ConnorGBrewster** [comment]
@jdm Agreed, I moved out the common code to a method inside Actions

**Comment by Ygg01** [comment]
Do you need this merged?

**Comment by jdm** [comment]
That would be nice, yes.

**Comment by Ygg01** [comment]
Ok, I'll bump the version and publish probably by the end of the day.

**Comment by ConnorGBrewster** [comment]
@Ygg01 do you have an update on when the new version will be published?

**Comment by Ygg01** [comment]
Couple of hours. Sorry to keep you waiting.

**Comment by ConnorGBrewster** [comment]
@Ygg01 no worries! Thanks! :)

**Comment by Ygg01** [comment]
Update was completed yesterday. xml5ever v0.1.2 should have this change.

**Pull request merged**
