### PR TITLE
More precise version constraints

### PR DESCRIPTION
**Pull request by mbrubeck**

### CODE REVIEW

**Comment by Ygg01** [comment]
Looks, good. Would you mind updating  CHANGELOG.md? I need to really add CONTRIBUTING.md 😅  at some point...

Also do you require crates.io permissions?

**Comment by mbrubeck** [comment]
Added a version bump and changelog. It looks like I already have crates.io permissions, so I'd be happy to publish this once it's merged, if you want.

**Comment by mbrubeck** [comment]
Published. Thanks!

**Comment by Ygg01** [comment]
No, thank you.

**Pull request merged**
